definitions:
  main.Book:
    properties:
      author:
        type: string
      id:
        description: |-
          ID คือ field ที่ต้องการรับเข้ามา
          int คือ type ของ field นั้น
          json:"id" คือ tag ที่ใช้เพื่อบอกว่า field นี้จะถูกแปลงเป็น json โดยใช้ชื่อ id แล้วจะแปลงให้อยู่ใน field ที่มีชื่อ ID ของ struct นี้ (map กับ struct แล้วได้ข้อมูลออกมา (เป็น json ต้องมี key ที่เป็น string และ value ที่เป็น string, number, boolean, array, object))
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /books:
    get:
      consumes:
      - application/json
      description: Get details of all books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Book'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Get all books
      tags:
      - books
swagger: "2.0"
